use std::{fs, path::Path};

use anyhow::Result;
use console::style;

use crate::{
    cli::{Cli, GenerateCiArgs},
    config::{Config, Ecosystem},
    ecosystem,
};

pub fn run(cli: &Cli, args: &GenerateCiArgs) -> Result<()> {
    let config = Config::load(&cli.config_path())?;
    let provider = args.provider.as_deref().unwrap_or(&config.ci.provider);

    if provider != "github" {
        anyhow::bail!("only 'github' provider is currently supported");
    }

    let repo_root = std::env::current_dir()?;
    let active_ecosystem = ecosystem::detect(&repo_root, Some(&config));
    let build_backend = ecosystem::python_build_backend(&repo_root);
    let yaml = generate_github_workflow(&config, active_ecosystem, build_backend.as_deref());

    if cli.dry_run {
        println!("{yaml}");
        return Ok(());
    }

    let workflow_path = Path::new(&config.ci.workflow_path);
    if let Some(parent) = workflow_path.parent() {
        fs::create_dir_all(parent)?;
    }

    if workflow_path.exists() {
        let existing = fs::read_to_string(workflow_path)?;
        if existing == yaml {
            println!("{} is already up to date", workflow_path.display());
            return Ok(());
        }
        println!("{} Existing workflow differs:", style("⚠").yellow());
        println!("{}", render_diff(&existing, &yaml));
        anyhow::bail!(
            "refusing to overwrite {} without review; run with --dry-run to inspect and replace manually",
            workflow_path.display()
        );
    }

    fs::write(workflow_path, &yaml)?;
    println!("Generated {}", style(workflow_path.display()).green());

    Ok(())
}

fn generate_github_workflow(
    config: &Config,
    active_ecosystem: Ecosystem,
    build_backend: Option<&str>,
) -> String {
    let branches = workflow_branches(config);
    let build_cmd = ecosystem::build_command(active_ecosystem, build_backend);
    let is_maturin = active_ecosystem == Ecosystem::Python
        && build_backend.is_some_and(|b| b.contains("maturin"));

    let mut yaml = String::new();
    yaml.push_str("# Generated by relx generate-ci - do not edit manually\n");
    yaml.push_str("# Re-generate with: relx generate-ci\n");
    if config.monorepo.enabled {
        yaml.push_str("# Note: monorepo mode is enabled\n");
    }
    yaml.push_str("name: Release\n");
    yaml.push('\n');
    yaml.push_str("on:\n");
    yaml.push_str("  push:\n");
    yaml.push_str(&format!("    branches: [{}]\n", branches.join(", ")));
    yaml.push('\n');
    yaml.push_str("permissions:\n");
    yaml.push_str("  contents: write\n");
    yaml.push_str("  pull-requests: write\n");
    yaml.push_str("  id-token: write\n");
    yaml.push('\n');
    yaml.push_str("jobs:\n");
    if config.monorepo.enabled
        && config.monorepo.release_mode == "per_package"
        && !config.monorepo.packages.is_empty()
    {
        for package in &config.monorepo.packages {
            let job_name = package.replace(['/', '.'], "-");
            yaml.push_str(&format!("  release-pr-{}:\n", job_name));
            yaml.push_str("    runs-on: ubuntu-latest\n");
            yaml.push_str("    steps:\n");
            yaml.push_str("      - uses: actions/checkout@v4\n");
            yaml.push_str("        with:\n");
            yaml.push_str("          fetch-depth: 0\n");
            yaml.push('\n');
            yaml.push_str("      - uses: ReleaseX/action@v1\n");
            yaml.push_str("        with:\n");
            yaml.push_str("          command: release pr\n");
            yaml.push_str("        env:\n");
            yaml.push_str("          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}\n");
        }
    } else {
        yaml.push_str("  release-pr:\n");
        yaml.push_str("    runs-on: ubuntu-latest\n");
        yaml.push_str("    steps:\n");
        yaml.push_str("      - uses: actions/checkout@v4\n");
        yaml.push_str("        with:\n");
        yaml.push_str("          fetch-depth: 0\n");
        yaml.push('\n');
        yaml.push_str("      - uses: ReleaseX/action@v1\n");
        yaml.push_str("        with:\n");
        yaml.push_str("          command: release pr\n");
        yaml.push_str("        env:\n");
        yaml.push_str("          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}\n");
    }

    if config.publish.enabled {
        yaml.push('\n');
        yaml.push_str("  publish:\n");
        yaml.push_str("    runs-on: ubuntu-latest\n");
        yaml.push_str("    if: startsWith(github.ref, 'refs/tags/')\n");
        yaml.push_str("    steps:\n");
        yaml.push_str("      - uses: actions/checkout@v4\n");
        yaml.push('\n');
        yaml.push_str("      - uses: astral-sh/setup-uv@v5\n");
        yaml.push('\n');
        if active_ecosystem == Ecosystem::Rust {
            yaml.push_str("      - uses: dtolnay/rust-toolchain@stable\n");
            yaml.push('\n');
            yaml.push_str(&format!("      - run: {}\n", build_cmd));
        } else if active_ecosystem == Ecosystem::Go {
            yaml.push_str("      - uses: actions/setup-go@v5\n");
            yaml.push_str("        with:\n");
            yaml.push_str("          go-version-file: go.mod\n");
            yaml.push('\n');
            yaml.push_str(&format!("      - run: {}\n", build_cmd));
        } else if is_maturin {
            yaml.push_str("      - uses: PyO3/maturin-action@v1\n");
            yaml.push_str("        with:\n");
            yaml.push_str("          command: build\n");
            yaml.push_str("          args: --release\n");
        } else {
            yaml.push_str(&format!("      - run: {}\n", build_cmd));
        }
        yaml.push('\n');
        yaml.push_str("      - uses: ReleaseX/action@v1\n");
        yaml.push_str("        with:\n");
        yaml.push_str("          command: release publish\n");
        yaml.push_str("        env:\n");
        yaml.push_str("          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}\n");
    }

    yaml
}

fn workflow_branches(config: &Config) -> Vec<String> {
    if !config.channels.is_empty() {
        let mut branches: Vec<String> = config
            .channels
            .iter()
            .map(|channel| channel.branch.clone())
            .collect();
        branches.sort();
        branches.dedup();
        return branches;
    }

    vec![config.release.branch.clone()]
}

fn render_diff(existing: &str, generated: &str) -> String {
    let old_lines: Vec<&str> = existing.lines().collect();
    let new_lines: Vec<&str> = generated.lines().collect();
    let mut output = String::new();
    let max = old_lines.len().max(new_lines.len());
    for idx in 0..max {
        match (old_lines.get(idx), new_lines.get(idx)) {
            (Some(old), Some(new)) if old == new => {
                output.push_str("  ");
                output.push_str(old);
            }
            (Some(old), Some(new)) => {
                output.push_str("- ");
                output.push_str(old);
                output.push('\n');
                output.push_str("+ ");
                output.push_str(new);
            }
            (Some(old), None) => {
                output.push_str("- ");
                output.push_str(old);
            }
            (None, Some(new)) => {
                output.push_str("+ ");
                output.push_str(new);
            }
            (None, None) => {}
        }
        output.push('\n');
    }
    output
}
