use std::{fs, path::Path};

use anyhow::Result;
use console::style;

use crate::{
    cli::{Cli, GenerateCiArgs},
    config::Config,
};

pub fn run(cli: &Cli, args: &GenerateCiArgs) -> Result<()> {
    let config = Config::load(&cli.config)?;
    let provider = args.provider.as_deref().unwrap_or(&config.ci.provider);

    if provider != "github" {
        anyhow::bail!("only 'github' provider is currently supported");
    }

    let build_backend = detect_build_backend();
    let yaml = generate_github_workflow(&config, &build_backend);

    if cli.dry_run {
        println!("{yaml}");
        return Ok(());
    }

    let workflow_path = Path::new(&config.ci.workflow_path);
    if let Some(parent) = workflow_path.parent() {
        fs::create_dir_all(parent)?;
    }

    if workflow_path.exists() {
        let existing = fs::read_to_string(workflow_path)?;
        if existing == yaml {
            println!("{} is already up to date", workflow_path.display());
            return Ok(());
        }
        println!("{} Existing workflow differs:", style("⚠").yellow());
        println!("{}", render_diff(&existing, &yaml));
        anyhow::bail!(
            "refusing to overwrite {} without review; run with --dry-run to inspect and replace manually",
            workflow_path.display()
        );
    }

    fs::write(workflow_path, &yaml)?;
    println!("Generated {}", style(workflow_path.display()).green());

    Ok(())
}

fn detect_build_backend() -> String {
    let path = Path::new("pyproject.toml");
    if !path.exists() {
        return "unknown".to_string();
    }

    let contents = match fs::read_to_string(path) {
        Ok(c) => c,
        Err(_) => return "unknown".to_string(),
    };

    let table = match contents.parse::<toml::Table>() {
        Ok(t) => t,
        Err(_) => return "unknown".to_string(),
    };

    table
        .get("build-system")
        .and_then(|bs| bs.as_table())
        .and_then(|bs| bs.get("build-backend"))
        .and_then(|bb| bb.as_str())
        .unwrap_or("unknown")
        .to_string()
}

fn build_command_for_backend(backend: &str) -> &str {
    if backend.contains("maturin") {
        "maturin build --release"
    } else {
        "uv build"
    }
}

fn generate_github_workflow(config: &Config, build_backend: &str) -> String {
    let branch = &config.release.branch;
    let build_cmd = build_command_for_backend(build_backend);
    let is_maturin = build_backend.contains("maturin");

    let mut yaml = String::new();
    yaml.push_str("# Generated by pyrls generate-ci — do not edit manually\n");
    yaml.push_str("# Re-generate with: pyrls generate-ci\n");
    if config.monorepo.enabled {
        yaml.push_str("# Note: monorepo mode is enabled\n");
    }
    yaml.push_str("name: Release\n");
    yaml.push('\n');
    yaml.push_str("on:\n");
    yaml.push_str("  push:\n");
    yaml.push_str(&format!("    branches: [{}]\n", branch));
    yaml.push('\n');
    yaml.push_str("permissions:\n");
    yaml.push_str("  contents: write\n");
    yaml.push_str("  pull-requests: write\n");
    yaml.push_str("  id-token: write\n");
    yaml.push('\n');
    yaml.push_str("jobs:\n");
    if config.monorepo.enabled
        && config.monorepo.release_mode == "per_package"
        && !config.monorepo.packages.is_empty()
    {
        for package in &config.monorepo.packages {
            let job_name = package.replace(['/', '.'], "-");
            yaml.push_str(&format!("  release-pr-{}:\n", job_name));
            yaml.push_str("    runs-on: ubuntu-latest\n");
            yaml.push_str("    steps:\n");
            yaml.push_str("      - uses: actions/checkout@v4\n");
            yaml.push_str("        with:\n");
            yaml.push_str("          fetch-depth: 0\n");
            yaml.push('\n');
            yaml.push_str("      - uses: pyrls/action@v1\n");
            yaml.push_str("        with:\n");
            yaml.push_str(&format!(
                "          command: release pr --channel {}\n",
                branch
            ));
            yaml.push_str("        env:\n");
            yaml.push_str("          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}\n");
        }
    } else {
        yaml.push_str("  release-pr:\n");
        yaml.push_str("    runs-on: ubuntu-latest\n");
        yaml.push_str("    steps:\n");
        yaml.push_str("      - uses: actions/checkout@v4\n");
        yaml.push_str("        with:\n");
        yaml.push_str("          fetch-depth: 0\n");
        yaml.push('\n');
        yaml.push_str("      - uses: pyrls/action@v1\n");
        yaml.push_str("        with:\n");
        yaml.push_str("          command: release pr\n");
        yaml.push_str("        env:\n");
        yaml.push_str("          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}\n");
    }

    if config.publish.enabled {
        yaml.push('\n');
        yaml.push_str("  publish:\n");
        yaml.push_str("    runs-on: ubuntu-latest\n");
        yaml.push_str("    if: startsWith(github.ref, 'refs/tags/')\n");
        yaml.push_str("    steps:\n");
        yaml.push_str("      - uses: actions/checkout@v4\n");
        yaml.push('\n');
        yaml.push_str("      - uses: astral-sh/setup-uv@v5\n");
        yaml.push('\n');
        if is_maturin {
            yaml.push_str("      - uses: PyO3/maturin-action@v1\n");
            yaml.push_str("        with:\n");
            yaml.push_str("          command: build\n");
            yaml.push_str("          args: --release\n");
        } else {
            yaml.push_str(&format!("      - run: {}\n", build_cmd));
        }
        yaml.push('\n');
        yaml.push_str("      - uses: pyrls/action@v1\n");
        yaml.push_str("        with:\n");
        yaml.push_str("          command: release publish\n");
        yaml.push_str("        env:\n");
        yaml.push_str("          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}\n");
    }

    yaml
}

fn render_diff(existing: &str, generated: &str) -> String {
    let old_lines: Vec<&str> = existing.lines().collect();
    let new_lines: Vec<&str> = generated.lines().collect();
    let mut output = String::new();
    let max = old_lines.len().max(new_lines.len());
    for idx in 0..max {
        match (old_lines.get(idx), new_lines.get(idx)) {
            (Some(old), Some(new)) if old == new => {
                output.push_str("  ");
                output.push_str(old);
            }
            (Some(old), Some(new)) => {
                output.push_str("- ");
                output.push_str(old);
                output.push('\n');
                output.push_str("+ ");
                output.push_str(new);
            }
            (Some(old), None) => {
                output.push_str("- ");
                output.push_str(old);
            }
            (None, Some(new)) => {
                output.push_str("+ ");
                output.push_str(new);
            }
            (None, None) => {}
        }
        output.push('\n');
    }
    output
}
